/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Section = IDL.Variant({
  'research' : IDL.Null,
  'poetry' : IDL.Null,
  'storytelling' : IDL.Null,
});
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'section' : Section,
  'updatedAt' : IDL.Int,
  'excerpt' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Work = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func(
      [Section, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [Entry],
      [],
    ),
  'createWork' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [Work], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteWork' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntry' : IDL.Func([IDL.Nat], [Entry], ['query']),
  'getWork' : IDL.Func([IDL.Nat], [Work], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPublishedBySection' : IDL.Func([Section], [IDL.Vec(Entry)], ['query']),
  'listPublishedWorks' : IDL.Func([], [IDL.Vec(Work)], ['query']),
  'publishEntry' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'publishWork' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'searchEntries' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'searchWorks' : IDL.Func([IDL.Text], [IDL.Vec(Work)], ['query']),
  'updateEntry' : IDL.Func(
      [
        IDL.Nat,
        Section,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Entry],
      [],
    ),
  'updateWork' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Work], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Section = IDL.Variant({
    'research' : IDL.Null,
    'poetry' : IDL.Null,
    'storytelling' : IDL.Null,
  });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'section' : Section,
    'updatedAt' : IDL.Int,
    'excerpt' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Work = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func(
        [Section, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [Entry],
        [],
      ),
    'createWork' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [Work], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteWork' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntry' : IDL.Func([IDL.Nat], [Entry], ['query']),
    'getWork' : IDL.Func([IDL.Nat], [Work], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPublishedBySection' : IDL.Func([Section], [IDL.Vec(Entry)], ['query']),
    'listPublishedWorks' : IDL.Func([], [IDL.Vec(Work)], ['query']),
    'publishEntry' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'publishWork' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'searchEntries' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'searchWorks' : IDL.Func([IDL.Text], [IDL.Vec(Work)], ['query']),
    'updateEntry' : IDL.Func(
        [
          IDL.Nat,
          Section,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Entry],
        [],
      ),
    'updateWork' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Work], []),
  });
};

export const init = ({ IDL }) => { return []; };