/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'section' : Section,
  'updatedAt' : bigint,
  'excerpt' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export type Section = { 'research' : null } |
  { 'poetry' : null } |
  { 'storytelling' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Work {
  'id' : bigint,
  'title' : string,
  'file' : ExternalBlob,
  'published' : boolean,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<
    [Section, string, string, Array<string>, [] | [string]],
    Entry
  >,
  'createWork' : ActorMethod<[string, string, ExternalBlob], Work>,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'deleteWork' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntry' : ActorMethod<[bigint], Entry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWork' : ActorMethod<[bigint], Work>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllEntries' : ActorMethod<[], Array<Entry>>,
  'listAllWorks' : ActorMethod<[], Array<Work>>,
  'listPublishedBySection' : ActorMethod<[Section], Array<Entry>>,
  'listPublishedWorks' : ActorMethod<[], Array<Work>>,
  'listRecentEntries' : ActorMethod<[bigint], Array<Entry>>,
  'listRecentWorks' : ActorMethod<[bigint], Array<Work>>,
  'publishEntry' : ActorMethod<[bigint, boolean], undefined>,
  'publishWork' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEntries' : ActorMethod<[string], Array<Entry>>,
  'searchEntriesByTag' : ActorMethod<[string], Array<Entry>>,
  'searchWorks' : ActorMethod<[string], Array<Work>>,
  'updateEntry' : ActorMethod<
    [bigint, Section, string, string, Array<string>, [] | [string]],
    Entry
  >,
  'updateWork' : ActorMethod<[bigint, string, string], Work>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];